// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: slims/pb/message_types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType enumerates the number associated to each packet tyoe
type MessageType int32

const (
	MessageType_UNKNOWN               MessageType = 0
	MessageType_FAULT                 MessageType = 1
	MessageType_HELLO                 MessageType = 2
	MessageType_HELLO_ACK             MessageType = 3
	MessageType_JOIN                  MessageType = 4
	MessageType_JOIN_ACCEPT           MessageType = 5
	MessageType_REGISTER              MessageType = 6
	MessageType_REGISTER_ACCEPT       MessageType = 7
	MessageType_DEREGISTER            MessageType = 8
	MessageType_DEREGISTER_ACK        MessageType = 9
	MessageType_MERGE                 MessageType = 10
	MessageType_MERGE_ACCEPT          MessageType = 11
	MessageType_INCREMENT             MessageType = 12
	MessageType_INCREMENT_ACK         MessageType = 13
	MessageType_SERVICE_HEARTBEAT     MessageType = 14
	MessageType_SERVICE_HEARTBEAT_ACK MessageType = 15
	MessageType_VK_HEARTBEAT          MessageType = 16
	MessageType_VK_HEARTBEAT_ACK      MessageType = 17
	// client
	MessageType_STATUS      MessageType = 18
	MessageType_STATUS_RESP MessageType = 19
	MessageType_LIST        MessageType = 20
	MessageType_LIST_ACK    MessageType = 21
	MessageType_LIST_RESP   MessageType = 22
	MessageType_GET         MessageType = 23
	MessageType_GET_RESP    MessageType = 24
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "FAULT",
		2:  "HELLO",
		3:  "HELLO_ACK",
		4:  "JOIN",
		5:  "JOIN_ACCEPT",
		6:  "REGISTER",
		7:  "REGISTER_ACCEPT",
		8:  "DEREGISTER",
		9:  "DEREGISTER_ACK",
		10: "MERGE",
		11: "MERGE_ACCEPT",
		12: "INCREMENT",
		13: "INCREMENT_ACK",
		14: "SERVICE_HEARTBEAT",
		15: "SERVICE_HEARTBEAT_ACK",
		16: "VK_HEARTBEAT",
		17: "VK_HEARTBEAT_ACK",
		18: "STATUS",
		19: "STATUS_RESP",
		20: "LIST",
		21: "LIST_ACK",
		22: "LIST_RESP",
		23: "GET",
		24: "GET_RESP",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":               0,
		"FAULT":                 1,
		"HELLO":                 2,
		"HELLO_ACK":             3,
		"JOIN":                  4,
		"JOIN_ACCEPT":           5,
		"REGISTER":              6,
		"REGISTER_ACCEPT":       7,
		"DEREGISTER":            8,
		"DEREGISTER_ACK":        9,
		"MERGE":                 10,
		"MERGE_ACCEPT":          11,
		"INCREMENT":             12,
		"INCREMENT_ACK":         13,
		"SERVICE_HEARTBEAT":     14,
		"SERVICE_HEARTBEAT_ACK": 15,
		"VK_HEARTBEAT":          16,
		"VK_HEARTBEAT_ACK":      17,
		"STATUS":                18,
		"STATUS_RESP":           19,
		"LIST":                  20,
		"LIST_ACK":              21,
		"LIST_RESP":             22,
		"GET":                   23,
		"GET_RESP":              24,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_slims_pb_message_types_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_slims_pb_message_types_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_slims_pb_message_types_proto_rawDescGZIP(), []int{0}
}

var File_slims_pb_message_types_proto protoreflect.FileDescriptor

const file_slims_pb_message_types_proto_rawDesc = "" +
	"\n" +
	"\x1cslims/pb/message_types.proto\x12\x03msg*\x95\x03\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05FAULT\x10\x01\x12\t\n" +
	"\x05HELLO\x10\x02\x12\r\n" +
	"\tHELLO_ACK\x10\x03\x12\b\n" +
	"\x04JOIN\x10\x04\x12\x0f\n" +
	"\vJOIN_ACCEPT\x10\x05\x12\f\n" +
	"\bREGISTER\x10\x06\x12\x13\n" +
	"\x0fREGISTER_ACCEPT\x10\a\x12\x0e\n" +
	"\n" +
	"DEREGISTER\x10\b\x12\x12\n" +
	"\x0eDEREGISTER_ACK\x10\t\x12\t\n" +
	"\x05MERGE\x10\n" +
	"\x12\x10\n" +
	"\fMERGE_ACCEPT\x10\v\x12\r\n" +
	"\tINCREMENT\x10\f\x12\x11\n" +
	"\rINCREMENT_ACK\x10\r\x12\x15\n" +
	"\x11SERVICE_HEARTBEAT\x10\x0e\x12\x19\n" +
	"\x15SERVICE_HEARTBEAT_ACK\x10\x0f\x12\x10\n" +
	"\fVK_HEARTBEAT\x10\x10\x12\x14\n" +
	"\x10VK_HEARTBEAT_ACK\x10\x11\x12\n" +
	"\n" +
	"\x06STATUS\x10\x12\x12\x0f\n" +
	"\vSTATUS_RESP\x10\x13\x12\b\n" +
	"\x04LIST\x10\x14\x12\f\n" +
	"\bLIST_ACK\x10\x15\x12\r\n" +
	"\tLIST_RESP\x10\x16\x12\a\n" +
	"\x03GET\x10\x17\x12\f\n" +
	"\bGET_RESP\x10\x18B7Z5github.com/rflandau/Orv/implementations/slims/orv/pb/b\x06proto3"

var (
	file_slims_pb_message_types_proto_rawDescOnce sync.Once
	file_slims_pb_message_types_proto_rawDescData []byte
)

func file_slims_pb_message_types_proto_rawDescGZIP() []byte {
	file_slims_pb_message_types_proto_rawDescOnce.Do(func() {
		file_slims_pb_message_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slims_pb_message_types_proto_rawDesc), len(file_slims_pb_message_types_proto_rawDesc)))
	})
	return file_slims_pb_message_types_proto_rawDescData
}

var file_slims_pb_message_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slims_pb_message_types_proto_goTypes = []any{
	(MessageType)(0), // 0: msg.MessageType
}
var file_slims_pb_message_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slims_pb_message_types_proto_init() }
func file_slims_pb_message_types_proto_init() {
	if File_slims_pb_message_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slims_pb_message_types_proto_rawDesc), len(file_slims_pb_message_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slims_pb_message_types_proto_goTypes,
		DependencyIndexes: file_slims_pb_message_types_proto_depIdxs,
		EnumInfos:         file_slims_pb_message_types_proto_enumTypes,
	}.Build()
	File_slims_pb_message_types_proto = out.File
	file_slims_pb_message_types_proto_goTypes = nil
	file_slims_pb_message_types_proto_depIdxs = nil
}
