// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: slims/pb/payloads.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NOTE(rlandau): at the time of writing, Go treats all enums as open.
// We'd much prefer they be closed. Alas.
// https://protobuf.dev/programming-guides/enum/
type Fault_FaultCode int32

const (
	Fault_UNKNOWN_TYPE Fault_FaultCode = 0
	Fault_B            Fault_FaultCode = 1 // TODO
)

// Enum value maps for Fault_FaultCode.
var (
	Fault_FaultCode_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "B",
	}
	Fault_FaultCode_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"B":            1,
	}
)

func (x Fault_FaultCode) Enum() *Fault_FaultCode {
	p := new(Fault_FaultCode)
	*p = x
	return p
}

func (x Fault_FaultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fault_FaultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_slims_pb_payloads_proto_enumTypes[0].Descriptor()
}

func (Fault_FaultCode) Type() protoreflect.EnumType {
	return &file_slims_pb_payloads_proto_enumTypes[0]
}

func (x Fault_FaultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fault_FaultCode.Descriptor instead.
func (Fault_FaultCode) EnumDescriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{0, 0}
}

// Type #1
// Negative response to any packet.
type Fault struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16 | echos the type number of the original packet
	Original      MessageType     `protobuf:"varint,1,opt,name=original,proto3,enum=msg.MessageType" json:"original,omitempty"`
	Errno         Fault_FaultCode `protobuf:"varint,2,opt,name=errno,proto3,enum=orv.Fault_FaultCode" json:"errno,omitempty"` // uint16 | the type of error, for automated testing
	Reason        string          `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                         // human-readable reason for rejecting this request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fault) Reset() {
	*x = Fault{}
	mi := &file_slims_pb_payloads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fault) ProtoMessage() {}

func (x *Fault) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fault.ProtoReflect.Descriptor instead.
func (*Fault) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *Fault) GetOriginal() MessageType {
	if x != nil {
		return x.Original
	}
	return MessageType_UNKNOWN
}

func (x *Fault) GetErrno() Fault_FaultCode {
	if x != nil {
		return x.Errno
	}
	return Fault_UNKNOWN_TYPE
}

func (x *Fault) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Type #3
// Response to a HELLO request.
type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // uint16
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_slims_pb_payloads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Type #4
// Requesting to join a vault.
type Join struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// is the node requesting to join the vault a VK?
	IsVk bool `protobuf:"varint,1,opt,name=is_vk,json=isVk,proto3" json:"is_vk,omitempty"`
	// required iff isVK | address at which the VK can receive requests/INCREMENTs
	VkAddr string `protobuf:"bytes,2,opt,name=vk_addr,json=vkAddr,proto3" json:"vk_addr,omitempty"`
	// uint16 | required iff isVK | height of the requestor node
	Height        uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_slims_pb_payloads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{2}
}

func (x *Join) GetIsVk() bool {
	if x != nil {
		return x.IsVk
	}
	return false
}

func (x *Join) GetVkAddr() string {
	if x != nil {
		return x.VkAddr
	}
	return ""
}

func (x *Join) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Type #5
// VK accepting the requestor to join underneath it.
// Once received, requestor can safely mark the VK as its parent.
type JoinAccept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16 | height of the accepting vk
	Height        uint32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAccept) Reset() {
	*x = JoinAccept{}
	mi := &file_slims_pb_payloads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAccept) ProtoMessage() {}

func (x *JoinAccept) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAccept.ProtoReflect.Descriptor instead.
func (*JoinAccept) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{3}
}

func (x *JoinAccept) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Type #6
// Sent by children to register a service to their parent.
type Register struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // name of the service to be registered
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // the address at which the service can be accessed
	// Go time string declaring how long
	// (w/o a heartbeat) until this service is considered prune-able
	Stale         string `protobuf:"bytes,3,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_slims_pb_payloads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{4}
}

func (x *Register) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Register) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Register) GetStale() string {
	if x != nil {
		return x.Stale
	}
	return ""
}

// Type #7
type RegisterAccept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the service that was registered
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccept) Reset() {
	*x = RegisterAccept{}
	mi := &file_slims_pb_payloads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccept) ProtoMessage() {}

func (x *RegisterAccept) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccept.ProtoReflect.Descriptor instead.
func (*RegisterAccept) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAccept) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Type #12
type ServiceHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the service that was registered
	Services      []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeat) Reset() {
	*x = ServiceHeartbeat{}
	mi := &file_slims_pb_payloads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeat) ProtoMessage() {}

func (x *ServiceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeat.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeat) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceHeartbeat) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// Type #13
type ServiceHeartbeatAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the services that were refreshed
	Refresheds []string `protobuf:"bytes,1,rep,name=refresheds,proto3" json:"refresheds,omitempty"`
	// name of services that were requested to be refreshed, but are unknown
	Unknowns      []string `protobuf:"bytes,2,rep,name=unknowns,proto3" json:"unknowns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeatAck) Reset() {
	*x = ServiceHeartbeatAck{}
	mi := &file_slims_pb_payloads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeatAck) ProtoMessage() {}

func (x *ServiceHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeatAck.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceHeartbeatAck) GetRefresheds() []string {
	if x != nil {
		return x.Refresheds
	}
	return nil
}

func (x *ServiceHeartbeatAck) GetUnknowns() []string {
	if x != nil {
		return x.Unknowns
	}
	return nil
}

// Response to a STATUS request
type StatusResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16
	Height uint32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// packed bytes; MSN is major, LSN is minor
	VersionsSupported []byte `protobuf:"bytes,2,opt,name=versions_supported,json=versionsSupported,proto3" json:"versions_supported,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResp) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StatusResp) GetVersionsSupported() []byte {
	if x != nil {
		return x.VersionsSupported
	}
	return nil
}

// Type #18
type List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16 | number of nodes to traverse (limited by root height)
	HopLimit      uint32 `protobuf:"varint,1,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_slims_pb_payloads_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{9}
}

func (x *List) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

// Type #19
type ListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of services known to the responding vk
	Services      []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{10}
}

func (x *ListResp) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// Type #20
type Get struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Service  string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                    //  the name of the desired service
	HopLimit uint32                 `protobuf:"varint,2,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"` // uint16
	// identifier created by the requestor so it can correlate a valid response
	Token         uint64 `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_slims_pb_payloads_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{11}
}

func (x *Get) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Get) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *Get) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

// Type #21
type GetResp struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	HostId  uint64                 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Service string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Address string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// echo of the token created by the requestor
	Token         uint64 `protobuf:"varint,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{12}
}

func (x *GetResp) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *GetResp) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetResp) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

var File_slims_pb_payloads_proto protoreflect.FileDescriptor

const file_slims_pb_payloads_proto_rawDesc = "" +
	"\n" +
	"\x17slims/pb/payloads.proto\x12\x03orv\x1a\x1cslims/pb/message_types.proto\"\x9f\x01\n" +
	"\x05Fault\x12,\n" +
	"\boriginal\x18\x01 \x01(\x0e2\x10.msg.MessageTypeR\boriginal\x12*\n" +
	"\x05errno\x18\x02 \x01(\x0e2\x14.orv.Fault.FaultCodeR\x05errno\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"$\n" +
	"\tFaultCode\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\x05\n" +
	"\x01B\x10\x01\"\"\n" +
	"\bHelloAck\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\"L\n" +
	"\x04Join\x12\x13\n" +
	"\x05is_vk\x18\x01 \x01(\bR\x04isVk\x12\x17\n" +
	"\avk_addr\x18\x02 \x01(\tR\x06vkAddr\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\"$\n" +
	"\n" +
	"JoinAccept\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\"T\n" +
	"\bRegister\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05stale\x18\x03 \x01(\tR\x05stale\"*\n" +
	"\x0eRegisterAccept\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\".\n" +
	"\x10ServiceHeartbeat\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"Q\n" +
	"\x13ServiceHeartbeatAck\x12\x1e\n" +
	"\n" +
	"refresheds\x18\x01 \x03(\tR\n" +
	"refresheds\x12\x1a\n" +
	"\bunknowns\x18\x02 \x03(\tR\bunknowns\"S\n" +
	"\n" +
	"StatusResp\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12-\n" +
	"\x12versions_supported\x18\x02 \x01(\fR\x11versionsSupported\"#\n" +
	"\x04List\x12\x1b\n" +
	"\thop_limit\x18\x01 \x01(\rR\bhopLimit\"&\n" +
	"\bListResp\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"R\n" +
	"\x03Get\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1b\n" +
	"\thop_limit\x18\x02 \x01(\rR\bhopLimit\x12\x14\n" +
	"\x05token\x18\x03 \x01(\x04R\x05token\"l\n" +
	"\aGetResp\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x04R\x06hostId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x04 \x01(\x04R\x05tokenB7Z5github.com/rflandau/Orv/implementations/slims/orv/pb/b\x06proto3"

var (
	file_slims_pb_payloads_proto_rawDescOnce sync.Once
	file_slims_pb_payloads_proto_rawDescData []byte
)

func file_slims_pb_payloads_proto_rawDescGZIP() []byte {
	file_slims_pb_payloads_proto_rawDescOnce.Do(func() {
		file_slims_pb_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slims_pb_payloads_proto_rawDesc), len(file_slims_pb_payloads_proto_rawDesc)))
	})
	return file_slims_pb_payloads_proto_rawDescData
}

var file_slims_pb_payloads_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slims_pb_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_slims_pb_payloads_proto_goTypes = []any{
	(Fault_FaultCode)(0),        // 0: orv.Fault.FaultCode
	(*Fault)(nil),               // 1: orv.Fault
	(*HelloAck)(nil),            // 2: orv.HelloAck
	(*Join)(nil),                // 3: orv.Join
	(*JoinAccept)(nil),          // 4: orv.JoinAccept
	(*Register)(nil),            // 5: orv.Register
	(*RegisterAccept)(nil),      // 6: orv.RegisterAccept
	(*ServiceHeartbeat)(nil),    // 7: orv.ServiceHeartbeat
	(*ServiceHeartbeatAck)(nil), // 8: orv.ServiceHeartbeatAck
	(*StatusResp)(nil),          // 9: orv.StatusResp
	(*List)(nil),                // 10: orv.List
	(*ListResp)(nil),            // 11: orv.ListResp
	(*Get)(nil),                 // 12: orv.Get
	(*GetResp)(nil),             // 13: orv.GetResp
	(MessageType)(0),            // 14: msg.MessageType
}
var file_slims_pb_payloads_proto_depIdxs = []int32{
	14, // 0: orv.Fault.original:type_name -> msg.MessageType
	0,  // 1: orv.Fault.errno:type_name -> orv.Fault.FaultCode
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_slims_pb_payloads_proto_init() }
func file_slims_pb_payloads_proto_init() {
	if File_slims_pb_payloads_proto != nil {
		return
	}
	file_slims_pb_message_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slims_pb_payloads_proto_rawDesc), len(file_slims_pb_payloads_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slims_pb_payloads_proto_goTypes,
		DependencyIndexes: file_slims_pb_payloads_proto_depIdxs,
		EnumInfos:         file_slims_pb_payloads_proto_enumTypes,
		MessageInfos:      file_slims_pb_payloads_proto_msgTypes,
	}.Build()
	File_slims_pb_payloads_proto = out.File
	file_slims_pb_payloads_proto_goTypes = nil
	file_slims_pb_payloads_proto_depIdxs = nil
}
