// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: slims/pb/payloads.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fault) Reset() {
	*x = Fault{}
	mi := &file_slims_pb_payloads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fault) ProtoMessage() {}

func (x *Fault) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fault.ProtoReflect.Descriptor instead.
func (*Fault) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *Fault) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Response to a STATUS request
type StatusResp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height uint32                 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"` //uint16
	// packed bytes; MSN is major, LSN is minor
	VersionsSupported []byte `protobuf:"bytes,2,opt,name=versions_supported,json=versionsSupported,proto3" json:"versions_supported,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResp) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StatusResp) GetVersionsSupported() []byte {
	if x != nil {
		return x.VersionsSupported
	}
	return nil
}

// Response to a HELLO request
type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // uint16
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_slims_pb_payloads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_slims_pb_payloads_proto protoreflect.FileDescriptor

const file_slims_pb_payloads_proto_rawDesc = "" +
	"\n" +
	"\x17slims/pb/payloads.proto\x12\x03orv\"\x1f\n" +
	"\x05Fault\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"S\n" +
	"\n" +
	"StatusResp\x12\x16\n" +
	"\x06Height\x18\x01 \x01(\rR\x06Height\x12-\n" +
	"\x12versions_supported\x18\x02 \x01(\fR\x11versionsSupported\"\"\n" +
	"\bHelloAck\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06heightB7Z5github.com/rflandau/Orv/implementations/slims/orv/pb/b\x06proto3"

var (
	file_slims_pb_payloads_proto_rawDescOnce sync.Once
	file_slims_pb_payloads_proto_rawDescData []byte
)

func file_slims_pb_payloads_proto_rawDescGZIP() []byte {
	file_slims_pb_payloads_proto_rawDescOnce.Do(func() {
		file_slims_pb_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slims_pb_payloads_proto_rawDesc), len(file_slims_pb_payloads_proto_rawDesc)))
	})
	return file_slims_pb_payloads_proto_rawDescData
}

var file_slims_pb_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_slims_pb_payloads_proto_goTypes = []any{
	(*Fault)(nil),      // 0: orv.Fault
	(*StatusResp)(nil), // 1: orv.StatusResp
	(*HelloAck)(nil),   // 2: orv.HelloAck
}
var file_slims_pb_payloads_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slims_pb_payloads_proto_init() }
func file_slims_pb_payloads_proto_init() {
	if File_slims_pb_payloads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slims_pb_payloads_proto_rawDesc), len(file_slims_pb_payloads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slims_pb_payloads_proto_goTypes,
		DependencyIndexes: file_slims_pb_payloads_proto_depIdxs,
		MessageInfos:      file_slims_pb_payloads_proto_msgTypes,
	}.Build()
	File_slims_pb_payloads_proto = out.File
	file_slims_pb_payloads_proto_goTypes = nil
	file_slims_pb_payloads_proto_depIdxs = nil
}
