// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: slims/pb/payloads.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fault_Errnos int32

const (
	// implementation-specific error, the equivalent of a 500 Internal
	// Server Error. Should be used as sparingly as possible.
	Fault_UNSPECIFIED            Fault_Errnos = 0
	Fault_UNKNOWN_TYPE           Fault_Errnos = 1 // sent when an unknown message type number is declared.
	Fault_BODY_NOT_ACCEPTED      Fault_Errnos = 2
	Fault_BODY_REQUIRED          Fault_Errnos = 3
	Fault_SHORTHAND_NOT_ACCEPTED Fault_Errnos = 4
	Fault_VERSION_NOT_SUPPORTED  Fault_Errnos = 5
	Fault_MALFORMED_BODY         Fault_Errnos = 6
	Fault_MALFORMED_ADDRESS      Fault_Errnos = 7
	Fault_UNKNOWN_CHILD_ID       Fault_Errnos = 8
	Fault_HELLO_REQUIRED         Fault_Errnos = 400
	Fault_BAD_HEIGHT             Fault_Errnos = 401
	Fault_ID_IN_USE              Fault_Errnos = 402
	Fault_BAD_SERVICE_NAME       Fault_Errnos = 600
	Fault_BAD_STALE_TIME         Fault_Errnos = 601
	Fault_ALL_UNKNOWN            Fault_Errnos = 1200
)

// Enum value maps for Fault_Errnos.
var (
	Fault_Errnos_name = map[int32]string{
		0:    "UNSPECIFIED",
		1:    "UNKNOWN_TYPE",
		2:    "BODY_NOT_ACCEPTED",
		3:    "BODY_REQUIRED",
		4:    "SHORTHAND_NOT_ACCEPTED",
		5:    "VERSION_NOT_SUPPORTED",
		6:    "MALFORMED_BODY",
		7:    "MALFORMED_ADDRESS",
		8:    "UNKNOWN_CHILD_ID",
		400:  "HELLO_REQUIRED",
		401:  "BAD_HEIGHT",
		402:  "ID_IN_USE",
		600:  "BAD_SERVICE_NAME",
		601:  "BAD_STALE_TIME",
		1200: "ALL_UNKNOWN",
	}
	Fault_Errnos_value = map[string]int32{
		"UNSPECIFIED":            0,
		"UNKNOWN_TYPE":           1,
		"BODY_NOT_ACCEPTED":      2,
		"BODY_REQUIRED":          3,
		"SHORTHAND_NOT_ACCEPTED": 4,
		"VERSION_NOT_SUPPORTED":  5,
		"MALFORMED_BODY":         6,
		"MALFORMED_ADDRESS":      7,
		"UNKNOWN_CHILD_ID":       8,
		"HELLO_REQUIRED":         400,
		"BAD_HEIGHT":             401,
		"ID_IN_USE":              402,
		"BAD_SERVICE_NAME":       600,
		"BAD_STALE_TIME":         601,
		"ALL_UNKNOWN":            1200,
	}
)

func (x Fault_Errnos) Enum() *Fault_Errnos {
	p := new(Fault_Errnos)
	*p = x
	return p
}

func (x Fault_Errnos) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fault_Errnos) Descriptor() protoreflect.EnumDescriptor {
	return file_slims_pb_payloads_proto_enumTypes[0].Descriptor()
}

func (Fault_Errnos) Type() protoreflect.EnumType {
	return &file_slims_pb_payloads_proto_enumTypes[0]
}

func (x Fault_Errnos) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fault_Errnos.Descriptor instead.
func (Fault_Errnos) EnumDescriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{0, 0}
}

// Type #1
// Negative response to any packet.
type Fault struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16 | echos the type number of the original packet
	Original MessageType `protobuf:"varint,1,opt,name=original,proto3,enum=msg.MessageType" json:"original,omitempty"`
	// uint16 | the type of error, for automated testing.
	// should be one of the above enums
	Errno          Fault_Errnos `protobuf:"varint,2,opt,name=errno,proto3,enum=orv.Fault_Errnos" json:"errno,omitempty"`
	AdditionalInfo *string      `protobuf:"bytes,3,opt,name=additional_info,json=additionalInfo,proto3,oneof" json:"additional_info,omitempty"` // (OPTIONAL)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Fault) Reset() {
	*x = Fault{}
	mi := &file_slims_pb_payloads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fault) ProtoMessage() {}

func (x *Fault) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fault.ProtoReflect.Descriptor instead.
func (*Fault) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *Fault) GetOriginal() MessageType {
	if x != nil {
		return x.Original
	}
	return MessageType_UNKNOWN
}

func (x *Fault) GetErrno() Fault_Errnos {
	if x != nil {
		return x.Errno
	}
	return Fault_UNSPECIFIED
}

func (x *Fault) GetAdditionalInfo() string {
	if x != nil && x.AdditionalInfo != nil {
		return *x.AdditionalInfo
	}
	return ""
}

// Type #2
// Initial greeting.
// Requiring prior to other, non-client-request packet chains.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_slims_pb_payloads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{1}
}

// Type #3
// Response to a HELLO request.
type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // uint16
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_slims_pb_payloads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Type #4
// Requesting to join a vault.
type Join struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// is the node requesting to join the vault a VK?
	IsVk bool `protobuf:"varint,1,opt,name=is_vk,json=isVk,proto3" json:"is_vk,omitempty"`
	// required iff isVK | address at which the VK can receive requests/INCREMENTs
	VkAddr string `protobuf:"bytes,2,opt,name=vk_addr,json=vkAddr,proto3" json:"vk_addr,omitempty"`
	// uint16 | required iff isVK | height of the requestor node
	Height        uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_slims_pb_payloads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{3}
}

func (x *Join) GetIsVk() bool {
	if x != nil {
		return x.IsVk
	}
	return false
}

func (x *Join) GetVkAddr() string {
	if x != nil {
		return x.VkAddr
	}
	return ""
}

func (x *Join) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Type #5
// VK accepting the requestor to join underneath it.
// Once received, requestor can safely mark the VK as its parent.
type JoinAccept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16 | height of the accepting vk
	Height        uint32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAccept) Reset() {
	*x = JoinAccept{}
	mi := &file_slims_pb_payloads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAccept) ProtoMessage() {}

func (x *JoinAccept) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAccept.ProtoReflect.Descriptor instead.
func (*JoinAccept) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{4}
}

func (x *JoinAccept) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Type #6
// Sent by children to register a service to their parent.
type Register struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // name of the service to be registered
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // the address at which the service can be accessed
	// Go time string declaring how long
	// (w/o a heartbeat) until this service is considered prune-able
	Stale         string `protobuf:"bytes,3,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_slims_pb_payloads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{5}
}

func (x *Register) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Register) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Register) GetStale() string {
	if x != nil {
		return x.Stale
	}
	return ""
}

// Type #7
type RegisterAccept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the service that was registered
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccept) Reset() {
	*x = RegisterAccept{}
	mi := &file_slims_pb_payloads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccept) ProtoMessage() {}

func (x *RegisterAccept) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccept.ProtoReflect.Descriptor instead.
func (*RegisterAccept) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAccept) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Type #12
type ServiceHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the service that was registered
	Services      []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeat) Reset() {
	*x = ServiceHeartbeat{}
	mi := &file_slims_pb_payloads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeat) ProtoMessage() {}

func (x *ServiceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeat.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeat) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceHeartbeat) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// Type #13
type ServiceHeartbeatAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the services that were refreshed
	Refresheds []string `protobuf:"bytes,1,rep,name=refresheds,proto3" json:"refresheds,omitempty"`
	// name of services that were requested to be refreshed, but are unknown
	Unknowns      []string `protobuf:"bytes,2,rep,name=unknowns,proto3" json:"unknowns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeatAck) Reset() {
	*x = ServiceHeartbeatAck{}
	mi := &file_slims_pb_payloads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeatAck) ProtoMessage() {}

func (x *ServiceHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeatAck.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceHeartbeatAck) GetRefresheds() []string {
	if x != nil {
		return x.Refresheds
	}
	return nil
}

func (x *ServiceHeartbeatAck) GetUnknowns() []string {
	if x != nil {
		return x.Unknowns
	}
	return nil
}

// Type #17.
// Response to a STATUS request.
// Closely resembles a VKSnapshot.
type StatusResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr  string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// packed bytes; MSN is major, LSN is minor
	VersionsSupported []byte  `protobuf:"bytes,4,opt,name=versions_supported,json=versionsSupported,proto3" json:"versions_supported,omitempty"`
	Height            uint32  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"` // uint16
	ParentId          *uint64 `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ParentAddr        *string `protobuf:"bytes,7,opt,name=parent_addr,json=parentAddr,proto3,oneof" json:"parent_addr,omitempty"`
	// Go time for pruning hellos that are not followed up on
	PruneTimesHello           *string           `protobuf:"bytes,8,opt,name=prune_times_hello,json=pruneTimesHello,proto3,oneof" json:"prune_times_hello,omitempty"`
	PruneTimesServicelessLeaf *string           `protobuf:"bytes,9,opt,name=prune_times_serviceless_leaf,json=pruneTimesServicelessLeaf,proto3,oneof" json:"prune_times_serviceless_leaf,omitempty"`
	PruneTimesChildVk         *string           `protobuf:"bytes,10,opt,name=prune_times_child_vk,json=pruneTimesChildVk,proto3,oneof" json:"prune_times_child_vk,omitempty"`
	ChildVks                  map[uint64]string `protobuf:"bytes,11,rep,name=child_vks,json=childVks,proto3" json:"child_vks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // nodeID -> address
	ChildLeaves               []uint64          `protobuf:"varint,12,rep,packed,name=child_leaves,json=childLeaves,proto3" json:"child_leaves,omitempty"`                                                           // nodeID
	Services                  map[string]string `protobuf:"bytes,13,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                  // service -> provider count
	AutoHbEnabled             *bool             `protobuf:"varint,14,opt,name=auto_hb_enabled,json=autoHbEnabled,proto3,oneof" json:"auto_hb_enabled,omitempty"`                                                    // does this vk have an autoheartbeater running?
	AutoHbFrequency           *string           `protobuf:"bytes,15,opt,name=auto_hb_frequency,json=autoHbFrequency,proto3,oneof" json:"auto_hb_frequency,omitempty"`                                               // Go time
	AutoHbBadLimit            *uint32           `protobuf:"varint,16,opt,name=auto_hb_bad_limit,json=autoHbBadLimit,proto3,oneof" json:"auto_hb_bad_limit,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusResp) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *StatusResp) GetVersionsSupported() []byte {
	if x != nil {
		return x.VersionsSupported
	}
	return nil
}

func (x *StatusResp) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StatusResp) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *StatusResp) GetParentAddr() string {
	if x != nil && x.ParentAddr != nil {
		return *x.ParentAddr
	}
	return ""
}

func (x *StatusResp) GetPruneTimesHello() string {
	if x != nil && x.PruneTimesHello != nil {
		return *x.PruneTimesHello
	}
	return ""
}

func (x *StatusResp) GetPruneTimesServicelessLeaf() string {
	if x != nil && x.PruneTimesServicelessLeaf != nil {
		return *x.PruneTimesServicelessLeaf
	}
	return ""
}

func (x *StatusResp) GetPruneTimesChildVk() string {
	if x != nil && x.PruneTimesChildVk != nil {
		return *x.PruneTimesChildVk
	}
	return ""
}

func (x *StatusResp) GetChildVks() map[uint64]string {
	if x != nil {
		return x.ChildVks
	}
	return nil
}

func (x *StatusResp) GetChildLeaves() []uint64 {
	if x != nil {
		return x.ChildLeaves
	}
	return nil
}

func (x *StatusResp) GetServices() map[string]string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *StatusResp) GetAutoHbEnabled() bool {
	if x != nil && x.AutoHbEnabled != nil {
		return *x.AutoHbEnabled
	}
	return false
}

func (x *StatusResp) GetAutoHbFrequency() string {
	if x != nil && x.AutoHbFrequency != nil {
		return *x.AutoHbFrequency
	}
	return ""
}

func (x *StatusResp) GetAutoHbBadLimit() uint32 {
	if x != nil && x.AutoHbBadLimit != nil {
		return *x.AutoHbBadLimit
	}
	return 0
}

// Type #18
type List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint16 | number of nodes to traverse (limited by root height)
	HopLimit      uint32 `protobuf:"varint,1,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_slims_pb_payloads_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{10}
}

func (x *List) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

// Type #19
type ListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of services known to the responding vk
	Services      []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{11}
}

func (x *ListResp) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// Type #20
type Get struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Service  string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                    //  the name of the desired service
	HopLimit uint32                 `protobuf:"varint,2,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"` // uint16
	// identifier created by the requestor so it can correlate a valid response
	Token         uint64 `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_slims_pb_payloads_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{12}
}

func (x *Get) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Get) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *Get) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

// Type #21
type GetResp struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	HostId  uint64                 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Service string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Address string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// echo of the token created by the requestor
	Token         uint64 `protobuf:"varint,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_slims_pb_payloads_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_slims_pb_payloads_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_slims_pb_payloads_proto_rawDescGZIP(), []int{13}
}

func (x *GetResp) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *GetResp) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetResp) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

var File_slims_pb_payloads_proto protoreflect.FileDescriptor

const file_slims_pb_payloads_proto_rawDesc = "" +
	"\n" +
	"\x17slims/pb/payloads.proto\x12\x03orv\x1a\x1cslims/pb/message_types.proto\"\xe4\x03\n" +
	"\x05Fault\x12,\n" +
	"\boriginal\x18\x01 \x01(\x0e2\x10.msg.MessageTypeR\boriginal\x12'\n" +
	"\x05errno\x18\x02 \x01(\x0e2\x11.orv.Fault.ErrnosR\x05errno\x12,\n" +
	"\x0fadditional_info\x18\x03 \x01(\tH\x00R\x0eadditionalInfo\x88\x01\x01\"\xc1\x02\n" +
	"\x06Errnos\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x01\x12\x15\n" +
	"\x11BODY_NOT_ACCEPTED\x10\x02\x12\x11\n" +
	"\rBODY_REQUIRED\x10\x03\x12\x1a\n" +
	"\x16SHORTHAND_NOT_ACCEPTED\x10\x04\x12\x19\n" +
	"\x15VERSION_NOT_SUPPORTED\x10\x05\x12\x12\n" +
	"\x0eMALFORMED_BODY\x10\x06\x12\x15\n" +
	"\x11MALFORMED_ADDRESS\x10\a\x12\x14\n" +
	"\x10UNKNOWN_CHILD_ID\x10\b\x12\x13\n" +
	"\x0eHELLO_REQUIRED\x10\x90\x03\x12\x0f\n" +
	"\n" +
	"BAD_HEIGHT\x10\x91\x03\x12\x0e\n" +
	"\tID_IN_USE\x10\x92\x03\x12\x15\n" +
	"\x10BAD_SERVICE_NAME\x10\xd8\x04\x12\x13\n" +
	"\x0eBAD_STALE_TIME\x10\xd9\x04\x12\x10\n" +
	"\vALL_UNKNOWN\x10\xb0\tB\x12\n" +
	"\x10_additional_info\"\a\n" +
	"\x05Hello\"\"\n" +
	"\bHelloAck\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\"L\n" +
	"\x04Join\x12\x13\n" +
	"\x05is_vk\x18\x01 \x01(\bR\x04isVk\x12\x17\n" +
	"\avk_addr\x18\x02 \x01(\tR\x06vkAddr\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\"$\n" +
	"\n" +
	"JoinAccept\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\"T\n" +
	"\bRegister\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05stale\x18\x03 \x01(\tR\x05stale\"*\n" +
	"\x0eRegisterAccept\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\".\n" +
	"\x10ServiceHeartbeat\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"Q\n" +
	"\x13ServiceHeartbeatAck\x12\x1e\n" +
	"\n" +
	"refresheds\x18\x01 \x03(\tR\n" +
	"refresheds\x12\x1a\n" +
	"\bunknowns\x18\x02 \x03(\tR\bunknowns\"\xbc\a\n" +
	"\n" +
	"StatusResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12-\n" +
	"\x12versions_supported\x18\x04 \x01(\fR\x11versionsSupported\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12 \n" +
	"\tparent_id\x18\x06 \x01(\x04H\x00R\bparentId\x88\x01\x01\x12$\n" +
	"\vparent_addr\x18\a \x01(\tH\x01R\n" +
	"parentAddr\x88\x01\x01\x12/\n" +
	"\x11prune_times_hello\x18\b \x01(\tH\x02R\x0fpruneTimesHello\x88\x01\x01\x12D\n" +
	"\x1cprune_times_serviceless_leaf\x18\t \x01(\tH\x03R\x19pruneTimesServicelessLeaf\x88\x01\x01\x124\n" +
	"\x14prune_times_child_vk\x18\n" +
	" \x01(\tH\x04R\x11pruneTimesChildVk\x88\x01\x01\x12:\n" +
	"\tchild_vks\x18\v \x03(\v2\x1d.orv.StatusResp.ChildVksEntryR\bchildVks\x12!\n" +
	"\fchild_leaves\x18\f \x03(\x04R\vchildLeaves\x129\n" +
	"\bservices\x18\r \x03(\v2\x1d.orv.StatusResp.ServicesEntryR\bservices\x12+\n" +
	"\x0fauto_hb_enabled\x18\x0e \x01(\bH\x05R\rautoHbEnabled\x88\x01\x01\x12/\n" +
	"\x11auto_hb_frequency\x18\x0f \x01(\tH\x06R\x0fautoHbFrequency\x88\x01\x01\x12.\n" +
	"\x11auto_hb_bad_limit\x18\x10 \x01(\rH\aR\x0eautoHbBadLimit\x88\x01\x01\x1a;\n" +
	"\rChildVksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_parent_addrB\x14\n" +
	"\x12_prune_times_helloB\x1f\n" +
	"\x1d_prune_times_serviceless_leafB\x17\n" +
	"\x15_prune_times_child_vkB\x12\n" +
	"\x10_auto_hb_enabledB\x14\n" +
	"\x12_auto_hb_frequencyB\x14\n" +
	"\x12_auto_hb_bad_limit\"#\n" +
	"\x04List\x12\x1b\n" +
	"\thop_limit\x18\x01 \x01(\rR\bhopLimit\"&\n" +
	"\bListResp\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"R\n" +
	"\x03Get\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1b\n" +
	"\thop_limit\x18\x02 \x01(\rR\bhopLimit\x12\x14\n" +
	"\x05token\x18\x03 \x01(\x04R\x05token\"l\n" +
	"\aGetResp\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x04R\x06hostId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x04 \x01(\x04R\x05tokenB7Z5github.com/rflandau/Orv/implementations/slims/orv/pb/b\x06proto3"

var (
	file_slims_pb_payloads_proto_rawDescOnce sync.Once
	file_slims_pb_payloads_proto_rawDescData []byte
)

func file_slims_pb_payloads_proto_rawDescGZIP() []byte {
	file_slims_pb_payloads_proto_rawDescOnce.Do(func() {
		file_slims_pb_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slims_pb_payloads_proto_rawDesc), len(file_slims_pb_payloads_proto_rawDesc)))
	})
	return file_slims_pb_payloads_proto_rawDescData
}

var file_slims_pb_payloads_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slims_pb_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_slims_pb_payloads_proto_goTypes = []any{
	(Fault_Errnos)(0),           // 0: orv.Fault.Errnos
	(*Fault)(nil),               // 1: orv.Fault
	(*Hello)(nil),               // 2: orv.Hello
	(*HelloAck)(nil),            // 3: orv.HelloAck
	(*Join)(nil),                // 4: orv.Join
	(*JoinAccept)(nil),          // 5: orv.JoinAccept
	(*Register)(nil),            // 6: orv.Register
	(*RegisterAccept)(nil),      // 7: orv.RegisterAccept
	(*ServiceHeartbeat)(nil),    // 8: orv.ServiceHeartbeat
	(*ServiceHeartbeatAck)(nil), // 9: orv.ServiceHeartbeatAck
	(*StatusResp)(nil),          // 10: orv.StatusResp
	(*List)(nil),                // 11: orv.List
	(*ListResp)(nil),            // 12: orv.ListResp
	(*Get)(nil),                 // 13: orv.Get
	(*GetResp)(nil),             // 14: orv.GetResp
	nil,                         // 15: orv.StatusResp.ChildVksEntry
	nil,                         // 16: orv.StatusResp.ServicesEntry
	(MessageType)(0),            // 17: msg.MessageType
}
var file_slims_pb_payloads_proto_depIdxs = []int32{
	17, // 0: orv.Fault.original:type_name -> msg.MessageType
	0,  // 1: orv.Fault.errno:type_name -> orv.Fault.Errnos
	15, // 2: orv.StatusResp.child_vks:type_name -> orv.StatusResp.ChildVksEntry
	16, // 3: orv.StatusResp.services:type_name -> orv.StatusResp.ServicesEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_slims_pb_payloads_proto_init() }
func file_slims_pb_payloads_proto_init() {
	if File_slims_pb_payloads_proto != nil {
		return
	}
	file_slims_pb_message_types_proto_init()
	file_slims_pb_payloads_proto_msgTypes[0].OneofWrappers = []any{}
	file_slims_pb_payloads_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slims_pb_payloads_proto_rawDesc), len(file_slims_pb_payloads_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slims_pb_payloads_proto_goTypes,
		DependencyIndexes: file_slims_pb_payloads_proto_depIdxs,
		EnumInfos:         file_slims_pb_payloads_proto_enumTypes,
		MessageInfos:      file_slims_pb_payloads_proto_msgTypes,
	}.Build()
	File_slims_pb_payloads_proto = out.File
	file_slims_pb_payloads_proto_goTypes = nil
	file_slims_pb_payloads_proto_depIdxs = nil
}
